### ISSUE TITLE
document options for crf.clj/train

### ISSUE THREAD

**Issue by behrica** [simongray/datalinguist#8]
As discussed , I want to document the `train` options properly as metadata.

This is rather easy to do, there is just one question,
namely if we should "clojurize" the options or not:
Should 
" :maxLeft " become ":max-left"  ?

There is a library, which does that in both directions automatically
https://github.com/clj-commons/camel-snake-kebab
so it would be easy.

It depends a bit "how close" your library want to stay in Java land vs. Clojure land.

I don't have a preference, I can do both.

Just decide, and let me know,

**Comment by behrica** [comment]
I just saw you use csk library already. Easier even, so just let me know your opinion if to convert the options to kebab case or not

**Comment by behrica** [comment]
I made a PR #9 ,
using options names as-are.
If you prefer kebab case, let me know, and I add the conversion

**Comment by simongray** [comment]
I think for the time being I would prefer the names as-are, but with the possibility of turning them into kebab case in the future. The things is, if these options are kebab-cased, then IMO all options should be. I'm leaning towards keywords being in kebab-case and strings using the names as-are, but this will require further code changes to the options conversion on my part. But from a compatibility PoV that makes the most sense to me, as it accommodates both views with each staying their line. I think reagent does something similar with HTML attributes.

AFAIK I currently only use csk to convert class names which would be really annoying to represent in their original form.
